### ISSUE TITLE
json~decode broken outside of 'json' namespace

### ISSUE THREAD

**Issue by erdg** [aw/picolisp-json#9]
The following happens with PL 15.11.0 (ubuntu 16.04 global install) and PL 17.11.19 (local install):
```
erik@thinkster2:~/code/pl/picolisp-json$ pil json.l +

: (json~encode '(("Hello" . "World")))
-> "{\"Hello\":\"World\"}"

: (json~decode @)                   
!? ((any (pack "json-" "Type" "-check")) "Name")   # from 'link-generic', see below
json-object-check -- Undefined
?
                
: (symbols 'json)
-> pico

json: (encode '(("Hello" . "World")))
-> "{\"Hello\":\"World\"}"

json: (decode @)                     
-> (("Hello" . "World"))
```
The line `((any (pack "json-" Type" "-check")) Name)` seems to build a symbol (in this case `json-object-check`) to be called as a function on `Name`. When called from outside the the `json` namespace, it still returns `json-object-check`, which is `local` to the `json` namespace and thus undefined.

The following is a quick fix that (seems) to work on my local copy:
```
erik@thinkster2:~/code/pl/picolisp-json$ git diff json.l
diff --git a/json.l b/json.l
index c25f792..13697ea 100644
--- a/json.l
+++ b/json.l
@@ -79,7 +79,7 @@
 [de link-generic (Type Bracket Iterator)
   (let Name (car *Json)
     (when Name
-          ((any (pack "json-" Type "-check")) Name)
+          ((any (if (= (symbols) 'json) (pack "json-" Type "-check") (pack "json~json-" Type "-check")) Name)
           (unless (= Bracket Name) (eval Iterator)) )
 
     (if (= Bracket (car *Json))
```
But this breaks all the unit tests, as `PIL_NAMESPACES` is set to false for testing:
```
erik@thinkster2:~/code/pl/picolisp-json$ make check 
PIL_NAMESPACES=false ./test.l
# MODULE_INFO redefined

  Testing JSON encoder/decoder for PicoLisp

"Unmatched JSON brackets '{'"
[test_json.l:96] json -- Bad symbol namespace
? 
```

**Comment by erdg** [comment]
And I needed a similar fix for the line `((any (pack "link-" "Type")))`, also in `link-generic`.

**Comment by aw** [comment]
Thanks for the bug report.

The issue with your fix is it will only work if the namespace is called `'json`.

OK I think I can fix this if I don't generate a symbol with `(any)`. I'll modify the library and run some tests.

**Comment by aw** [comment]
@erdg This should be fixed in the latest commit to `master` (I will tag it `v3.3.0`). Please note, namespaces with this library will not work in versions of PicoLisp `>= 17.3.4` due a breaking change introduced in that version. I haven't taken the time to modify my code to fix that issue, but I'll get around to it eventually.

**Comment by erdg** [comment]
Cool, thanks!
